#!/usr/bin/env python

#########################################################################
# A provisional routine for actually producing and returning data cubes.
#########################################################################

from charis import extractcube
import numpy as np
from builtins import range
import time
import sys
import re
import os
import multiprocessing
import glob
import configparser

from future import standard_library

standard_library.install_aliases()


if __name__ == "__main__":

    if len(sys.argv) < 3:
        errstring = "Must call extractcube.py with at least two arguments:\n"
        errstring += "1: string(s) parsed by glob matching files to be turned into data cubes\n"
        errstring += "2: a .ini configuration file processed by ConfigParser"
        print(errstring)
        exit()

    filenames = []
    for i in range(1, len(sys.argv) - 1):
        filenames += glob.glob(sys.argv[i])

    if len(filenames) == 0:
        raise ValueError("No matching CHARIS files found by extractcube.")

    Config = configparser.ConfigParser()
    Config.read(sys.argv[len(sys.argv) - 1])

    read_0 = Config.getint('Ramp', 'read_0')
    try:
        read_1 = Config.getint('Ramp', 'read_f')
    except Exception:
        read_1 = None
    read_idx = [read_0, read_1]
    try:
        gain = Config.getfloat('Ramp', 'gain')
    except Exception:
        gain = 2
    try:
        noisefac = Config.getfloat('Ramp', 'noisefac')
    except Exception:
        noisefac = 0
    try:
        saveramp = Config.getboolean('Ramp', 'saveramp')
    except Exception:
        saveramp = True
    try:
        bgsub = Config.getboolean('Calib', 'bgsub')
    except Exception:
        bgsub = True
    try:
        mask = Config.getboolean('Calib', 'mask')
    except Exception:
        mask = True
    # try:
    #     fixbadpixels = Config.getboolean('Calib', 'fixbadpixels')
    # except:
    #     fixbadpixels = False
    try:
        flatfield = Config.getboolean('Calib', 'flatfield')
    except Exception:
        flatfield = True
    try:
        fitshift = Config.getboolean('Calib', 'fitshift')
    except Exception:
        fitshift = True

    calibdir = Config.get('Calib', 'calibdir')
    R = Config.getint('Extract', 'R')
    method = Config.get('Extract', 'method')
    try:
        refine = Config.getboolean('Extract', 'refine')
    except Exception:
        refine = True
    try:
        crosstalk_scale = Config.getfloat('Extract', 'crosstalkscale')
    except Exception:
        crosstalk_scale = 1.0
    try:
        dc_xtalk_correction = Config.getboolean('Extract', 'dcxtalkcorrection')
    except Exception:
        dc_xtalk_correction = False
    try:
        linear_wavelength = Config.getboolean('Extract', 'linearwavelength')
    except Exception:
        linear_wavelength = False
    try:
        suppressrn = Config.getboolean('Extract', 'suppressrn')
    except Exception:
        suppressrn = True
    try:
        minpct = Config.getint('Extract', 'minpct')
        minpct = max(minpct, 0)
        # Don't allow more than 90% of the pixels to be used in estimating the read noise.
        minpct = min(minpct, 90)
    except Exception:
        minpct = 60
    try:
        fitbkgnd = Config.getboolean('Extract', 'fitbkgnd')
    except Exception:
        fitbkgnd = True
    try:
        saveresid = Config.getboolean('Extract', 'saveresid')
    except Exception:
        saveresid = False

    ################################################################
    # Maximum threads must be between 1 and cpu_count, inclusive
    ################################################################

    try:
        maxcpus = Config.getint('Extract', 'maxcpus')
        if maxcpus <= 0:
            maxcpus = multiprocessing.cpu_count() + maxcpus
        maxcpus = min(maxcpus, multiprocessing.cpu_count())
        maxcpus = max(maxcpus, 1)
    except Exception:
        maxcpus = multiprocessing.cpu_count()

    try:
        smoothandmask = Config.getboolean('Extract', 'smoothandmask')
    except Exception:
        smoothandmask = True

    for filename in filenames:
        _ = extractcube.getcube(
            filename=filename, read_idx=read_idx, bgsub=bgsub,
            bgpath=None, mask=mask,
            gain=gain, noisefac=noisefac,
            saveramp=saveramp, refine=refine,
            crosstalk_scale=crosstalk_scale,
            dc_xtalk_correction=dc_xtalk_correction,
            linear_wavelength=linear_wavelength,
            maxcpus=maxcpus,
            calibdir=calibdir, R=R, method=method,
            smoothandmask=smoothandmask, flatfield=flatfield,
            fitshift=fitshift, suppressrn=suppressrn,
            minpct=minpct, fitbkgnd=fitbkgnd,
            saveresid=saveresid)

    # for filename in filenames:
    #     for read_idx in range(ndit):
    #         _ = extractcube.getcube(
    #             filename=filename, read_idx=read_idx, bgsub=bgsub,
    #             bgpath=None,
    #             mask=mask, gain=gain, noisefac=noisefac,
    #             saveramp=saveramp, refine=refine, maxcpus=maxcpus,
    #             calibdir=calibdir, R=R, method=method,
    #             smoothandmask=smoothandmask, flatfield=flatfield,
    #             fitshift=fitshift, suppressrn=suppressrn,
    #             minpct=minpct, fitbkgnd=fitbkgnd,
    #             saveresid=saveresid)
